### ISSUE TITLE
"Five Nights at Gorilla's" does not actually download.

### ISSUE THREAD

**Issue by EditDungeonIsTheBest** [MrBanana01/MonkeModList#1]
When I try to use this mod to download "Five Nights at Gorilla's", it says that the download was successful but the file for it is not in the plugins folder. All other mod downloads work just fine though.

**Comment by MrBanana01** [comment]
I will see the issue tmr, it might have to do with zip files but thanks for letting me know!

**Comment by MrBanana01** [comment]
Sorry I was very tired and never asked if you could download files that are in zip format or if you were in steam

**Comment by MrBanana01** [comment]
This should be fixed in 1.0.3
