### ISSUE TITLE
The mod I have created will not update.

### ISSUE THREAD

**Issue by SteveTheAnimator** [MrBanana01/MonkeModList#2]
read the title

**Comment by MrBanana01** [comment]
There might be an issue with installing mods, please wait

**Comment by MrBanana01** [comment]
This might be because your on steam vr, I have no idea why but the steam vr version of gtag sometimes can't download the needed files to update mods

**Comment by SteveTheAnimator** [comment]
Nevermind, it was just the list not being updated.
